### ISSUE TITLE
model外键统一处理

### ISSUE THREAD

**Issue by helloyou2012** [d-band/qingloo#1]
将外键统一拿到外面，保证model的简洁性

**Comment by lkisme** [comment]
我对sequenlize并不是很熟，我看它的document上 http://docs.sequelizejs.com/en/latest/docs/models-definition/ 这一节是这么定义的，那种hasMany，hasOne出现在过这一节：Working with legacy tables:  http://docs.sequelizejs.com/en/latest/docs/legacy/ , so I though it is implied this format would be better accord

**Comment by helloyou2012** [comment]
应该都可以，不过感觉后面的那种清晰一点，我把这几个表改了：`comment/group/group_members/reply/topic/user`，后面几个表应该暂时还用不到，先用这几个表吧，后面有需要在修改后面几个表

**Comment by lkisme** [comment]
怎么我看好多column都去掉了？

**Comment by lkisme** [comment]
改了之后没有跑，有空再跑一下试试
